/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuanTriRouteImport } from './routes/quan-tri'
import { Route as HuongDanRouteImport } from './routes/huong-dan'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiaDiemIndexRouteImport } from './routes/dia-diem.index'
import { Route as KhuVucSlugRouteImport } from './routes/khu-vuc.$slug'
import { Route as DiaDiemSlugRouteImport } from './routes/dia-diem.$slug'

const QuanTriRoute = QuanTriRouteImport.update({
  id: '/quan-tri',
  path: '/quan-tri',
  getParentRoute: () => rootRouteImport,
} as any)
const HuongDanRoute = HuongDanRouteImport.update({
  id: '/huong-dan',
  path: '/huong-dan',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaDiemIndexRoute = DiaDiemIndexRouteImport.update({
  id: '/dia-diem/',
  path: '/dia-diem/',
  getParentRoute: () => rootRouteImport,
} as any)
const KhuVucSlugRoute = KhuVucSlugRouteImport.update({
  id: '/khu-vuc/$slug',
  path: '/khu-vuc/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaDiemSlugRoute = DiaDiemSlugRouteImport.update({
  id: '/dia-diem/$slug',
  path: '/dia-diem/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/huong-dan': typeof HuongDanRoute
  '/quan-tri': typeof QuanTriRoute
  '/dia-diem/$slug': typeof DiaDiemSlugRoute
  '/khu-vuc/$slug': typeof KhuVucSlugRoute
  '/dia-diem/': typeof DiaDiemIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/huong-dan': typeof HuongDanRoute
  '/quan-tri': typeof QuanTriRoute
  '/dia-diem/$slug': typeof DiaDiemSlugRoute
  '/khu-vuc/$slug': typeof KhuVucSlugRoute
  '/dia-diem': typeof DiaDiemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/huong-dan': typeof HuongDanRoute
  '/quan-tri': typeof QuanTriRoute
  '/dia-diem/$slug': typeof DiaDiemSlugRoute
  '/khu-vuc/$slug': typeof KhuVucSlugRoute
  '/dia-diem/': typeof DiaDiemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gioi-thieu'
    | '/huong-dan'
    | '/quan-tri'
    | '/dia-diem/$slug'
    | '/khu-vuc/$slug'
    | '/dia-diem/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gioi-thieu'
    | '/huong-dan'
    | '/quan-tri'
    | '/dia-diem/$slug'
    | '/khu-vuc/$slug'
    | '/dia-diem'
  id:
    | '__root__'
    | '/'
    | '/gioi-thieu'
    | '/huong-dan'
    | '/quan-tri'
    | '/dia-diem/$slug'
    | '/khu-vuc/$slug'
    | '/dia-diem/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GioiThieuRoute: typeof GioiThieuRoute
  HuongDanRoute: typeof HuongDanRoute
  QuanTriRoute: typeof QuanTriRoute
  DiaDiemSlugRoute: typeof DiaDiemSlugRoute
  KhuVucSlugRoute: typeof KhuVucSlugRoute
  DiaDiemIndexRoute: typeof DiaDiemIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quan-tri': {
      id: '/quan-tri'
      path: '/quan-tri'
      fullPath: '/quan-tri'
      preLoaderRoute: typeof QuanTriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huong-dan': {
      id: '/huong-dan'
      path: '/huong-dan'
      fullPath: '/huong-dan'
      preLoaderRoute: typeof HuongDanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dia-diem/': {
      id: '/dia-diem/'
      path: '/dia-diem'
      fullPath: '/dia-diem/'
      preLoaderRoute: typeof DiaDiemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khu-vuc/$slug': {
      id: '/khu-vuc/$slug'
      path: '/khu-vuc/$slug'
      fullPath: '/khu-vuc/$slug'
      preLoaderRoute: typeof KhuVucSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dia-diem/$slug': {
      id: '/dia-diem/$slug'
      path: '/dia-diem/$slug'
      fullPath: '/dia-diem/$slug'
      preLoaderRoute: typeof DiaDiemSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GioiThieuRoute: GioiThieuRoute,
  HuongDanRoute: HuongDanRoute,
  QuanTriRoute: QuanTriRoute,
  DiaDiemSlugRoute: DiaDiemSlugRoute,
  KhuVucSlugRoute: KhuVucSlugRoute,
  DiaDiemIndexRoute: DiaDiemIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
