/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiaDiemIndexRouteImport } from './routes/dia-diem.index'
import { Route as KhuVucSlugRouteImport } from './routes/khu-vuc.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaDiemIndexRoute = DiaDiemIndexRouteImport.update({
  id: '/dia-diem/',
  path: '/dia-diem/',
  getParentRoute: () => rootRouteImport,
} as any)
const KhuVucSlugRoute = KhuVucSlugRouteImport.update({
  id: '/khu-vuc/$slug',
  path: '/khu-vuc/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/khu-vuc/$slug': typeof KhuVucSlugRoute
  '/dia-diem/': typeof DiaDiemIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/khu-vuc/$slug': typeof KhuVucSlugRoute
  '/dia-diem': typeof DiaDiemIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/khu-vuc/$slug': typeof KhuVucSlugRoute
  '/dia-diem/': typeof DiaDiemIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/khu-vuc/$slug' | '/dia-diem/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/khu-vuc/$slug' | '/dia-diem'
  id: '__root__' | '/' | '/khu-vuc/$slug' | '/dia-diem/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KhuVucSlugRoute: typeof KhuVucSlugRoute
  DiaDiemIndexRoute: typeof DiaDiemIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dia-diem/': {
      id: '/dia-diem/'
      path: '/dia-diem'
      fullPath: '/dia-diem/'
      preLoaderRoute: typeof DiaDiemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khu-vuc/$slug': {
      id: '/khu-vuc/$slug'
      path: '/khu-vuc/$slug'
      fullPath: '/khu-vuc/$slug'
      preLoaderRoute: typeof KhuVucSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KhuVucSlugRoute: KhuVucSlugRoute,
  DiaDiemIndexRoute: DiaDiemIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
